import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} nested`}>
        <h1 className="text-2xl my-4">
          👑 This is root {`\`/(docs)/docs/layout.tsx\``}
        </h1>
        {children}
      </body>
    </html>
  );
}
